const express = require("express");
const router = express.Router();
const { crearContactoHandler, obtenerContactosHandler, obtenerContactosPorClienteHandler, obtenerContactoPorIdHandler, actualizarContactoHandler, eliminarContactoHandler } = require("../handlers/contactoHandler");
const roleAuth = require("../checkers/roleAuth");
router.post("/", roleAuth(["all_access","create_contactos"]), crearContactoHandler);
router.get("/", roleAuth(["all_access","read_contactos"]), obtenerContactosHandler);
router.get("/cliente/:clienteId", roleAuth(["all_access","read_contactos"]), obtenerContactosPorClienteHandler);
router.get("/:id", roleAuth(["all_access","read_contactos"]), obtenerContactoPorIdHandler);
router.put("/:id", roleAuth(["all_access","update_contactos"]), actualizarContactoHandler);
router.delete("/:id", roleAuth(["all_access","delete_contactos"]), eliminarContactoHandler);
module.exports = router;