const express = require("express");
const router = express.Router();
const handler = require("../handlers/ordenTrabajoHandler");
const roleAuth = require("../checkers/roleAuth");
router.post("/", roleAuth(["all_access","create_ordenes_trabajo"]), handler.crearOrdenTrabajoHandler);
router.get("/", roleAuth(["all_access","read_ordenes_trabajo"]), handler.obtenerOrdenesTrabajoHandler);
router.get("/aviso/:avisoId/solicitudes-pendientes", roleAuth(["all_access","read_ordenes_trabajo"]), handler.obtenerSolicitudesGeneralesPendientesHandler);
router.get("/:id", roleAuth(["all_access","read_ordenes_trabajo"]), handler.obtenerOrdenTrabajoPorIdHandler);
router.patch("/:id/completa", roleAuth(["all_access","update_ordenes_trabajo"]), handler.actualizarOrdenTrabajoCompletaHandler);
router.delete("/:id", roleAuth(["all_access","delete_ordenes_trabajo"]), handler.eliminarOrdenTrabajoHandler);
router.get("/:id/verificar-liberacion", roleAuth(["all_access","read_ordenes_trabajo"]), handler.verificarLiberacionHandler);
router.patch("/:id/liberar", roleAuth(["all_access","update_ordenes_trabajo"]), handler.liberarOrdenTrabajoHandler);
router.get("/:id/solicitudes", roleAuth(["all_access","read_ordenes_trabajo"]), handler.obtenerSolicitudesPorOTHandler);
router.get("/:id/preview-solicitudes", roleAuth(["all_access","read_ordenes_trabajo"]), handler.previewSolicitudesHandler);
router.post("/:id/generar-solicitud-compra", roleAuth(["all_access","create_solicitudes_compra"]), handler.generarSolicitudCompraHandler);
router.post("/:id/generar-solicitud-almacen", roleAuth(["all_access","create_solicitudes_almacen"]), handler.generarSolicitudAlmacenHandler);
router.post("/:id/asignar-solicitud-general", roleAuth(["all_access","update_ordenes_trabajo"]), handler.asignarSolicitudGeneralAOTHandler);
router.post("/:id/solicitud-compra/general", roleAuth(["all_access","create_solicitudes_compra"]), handler.crearSolicitudCompraGeneralHandler);
router.post("/:id/solicitud-almacen/general", roleAuth(["all_access","create_solicitudes_almacen"]), handler.crearSolicitudAlmacenGeneralHandler);
router.post("/:id/sync-sap", roleAuth(["all_access","update_ordenes_trabajo"]), handler.syncSAPOrdenTrabajoHandler);
router.post("/:id/sync-almacen", roleAuth(["all_access","update_ordenes_trabajo"]), handler.syncAlmacenOrdenTrabajoHandler);
router.get("/:id/solicitudes-tratamiento", roleAuth(["all_access","read_ordenes_trabajo"]), handler.getDetalleSolicitudesTratamientoPorOrdenTrabajoHandler);
module.exports = router;