const { Router } = require("express");
const { crearPais, listarPaises, obtenerPais, actualizarPais, eliminarPais } = require("../handlers/paisHandler");
const roleAuth = require("../checkers/roleAuth");
const router = Router();
router.post("/", roleAuth(["all_access","create_paises"]), crearPais);
router.get("/", roleAuth(["all_access","read_paises"]), listarPaises);
router.get("/:id", roleAuth(["all_access","read_paises"]), obtenerPais);
router.put("/:id", roleAuth(["all_access","update_paises"]), actualizarPais);
router.delete("/:id", roleAuth(["all_access","delete_paises"]), eliminarPais);
module.exports = router;